version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1

    ############
    # Workflows
    ############

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
    ########
    # JOBS
    #######
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://postgres@localhost/mediminderx_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mediminderx_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Python dependecies in a venv environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

    ###########
    # DEPLOYS
    ##########

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Deploy Mediminderx to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master